<script setup>
import { useWorkPlaceStore } from "@/store/Admin/Company/WorkPlace";

const form = useWorkPlaceStore().form;
</script>
<template>
  <div class="table-responsive">
    <table class="table table-hover table-striped mt-3" style="cursor: pointer">
      <thead>
        <tr class="fw-bold text-gray-800 border-bottom-2 border-gray-200">
          <th style="width: 150px">{{ $t("workType") }}</th>
          <th style="width: 200px">{{ $t("startTime") }}</th>
          <th style="width: 200px">{{ $t("endTime") }}</th>
          <th style="width: 100px">{{ $t("breakTime") }}</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            {{ $t("morning") }}
          </td>
          <td>
            <Input
              v-model="form.morning.start_time"
              :label="$t('startTime')"
              name="morning_start_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
              rules="max:5|min:4"
            />
          </td>
          <td>
            <Input
              v-model="form.morning.end_time"
              :label="$t('endTime')"
              name="morning_end_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.morning.break_time"
              :label="$t('breakTime')"
              name="morning_break_time"
              :inline="false"
              :showLabel="false"
            />
          </td>
        </tr>
        <tr>
          <td>
            {{ $t("afternoon") }}
          </td>
          <td>
            <Input
              v-model="form.afternoon.start_time"
              :label="$t('startTime')"
              name="afternoon_start_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.afternoon.end_time"
              :label="$t('endTime')"
              name="afternoon_end_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.afternoon.break_time"
              :label="$t('breakTime')"
              name="afternoon_break_time"
              :inline="false"
              :showLabel="false"
            />
          </td>
        </tr>
        <tr>
          <td>
            {{ $t("night") }}
          </td>
          <td>
            <Input
              v-model="form.night.start_time"
              :label="$t('startTime')"
              name="night_start_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.night.end_time"
              :label="$t('endTime')"
              name="night_end_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.night.break_time"
              :label="$t('breakTime')"
              name="night_break_time"
              :inline="false"
              :showLabel="false"
            />
          </td>
        </tr>
        <tr>
          <td>
            {{ $t("fullDay") }}
          </td>
          <td>
            <Input
              v-model="form.full.start_time"
              :label="$t('startTime')"
              name="full_start_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.full.end_time"
              :label="$t('endTime')"
              name="full_end_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.full.break_time"
              :label="$t('breakTime')"
              name="full_break_time"
              :inline="false"
              :showLabel="false"
            />
          </td>
        </tr>
        <tr>
          <td>
            {{ $t("report") }}
          </td>
          <td>
            <Input
              v-model="form.report.start_time"
              :label="$t('startTime')"
              name="report_start_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.report.end_time"
              :label="$t('endTime')"
              name="report_end_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.report.break_time"
              :label="$t('breakTime')"
              name="report_break_time"
              :inline="false"
              :showLabel="false"
            />
          </td>
        </tr>
        <tr>
          <td>
            {{ $t("annual") }}
          </td>
          <td>
            <Input
              v-model="form.annual.start_time"
              :label="$t('startTime')"
              name="annual_start_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.annual.end_time"
              :label="$t('endTime')"
              name="annual_end_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.annual.break_time"
              :label="$t('breakTime')"
              name="annual_break_time"
              :inline="false"
              :showLabel="false"
            />
          </td>
        </tr>

        <tr>
          <td>
            {{ $t("permit") }}
          </td>
          <td>
            <Input
              v-model="form.permit.start_time"
              :label="$t('startTime')"
              name="permit_start_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.permit.end_time"
              :label="$t('endTime')"
              name="permit_end_time"
              :inline="false"
              :showLabel="false"
              :isMask="true"
              mask="##:##"
            />
          </td>
          <td>
            <Input
              v-model="form.permit.break_time"
              :label="$t('breakTime')"
              name="permit_break_time"
              :inline="false"
              :showLabel="false"
            />
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
